# Generated by Django 4.2.16 on 2024-09-07 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="nom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="prenom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="statut",
            field=models.CharField(default="extérieur", max_length=100),
        ),
        migrations.AlterField(
            model_name="participant",
            name="cotisant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.cotisant",
            ),
        ),
    ]
