# Generated by Django 4.2.16 on 2024-09-07 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_participant_nom_participant_prenom_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_bannissement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "duree_bannissement",
                    models.IntegerField(help_text="Durée du bannissement en jours"),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("Sanction", "Sanction"),
                            ("Mesure préventive", "Mesure préventive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cotisant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banni",
                        to="events.cotisant",
                    ),
                ),
            ],
        ),
    ]
