# Generated by Django 4.2.16 on 2024-09-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_banni"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="identifiant",
            field=models.CharField(
                default="ouistiti",
                help_text="Choisissez un identifiant pour sécuriser l'accès à cet événement.",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
