# Generated by Django 4.2.16 on 2024-09-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_evenement_identifiant"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="participants",
            field=models.ManyToManyField(
                through="events.Participant", to="events.cotisant"
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="cotisant",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.cotisant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="participant",
            name="evenement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.evenement"
            ),
        ),
    ]
