# Generated by Django 4.2.16 on 2024-09-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_evenement_participants_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="nom",
            field=models.CharField(default="name", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="participant",
            name="prenom",
            field=models.CharField(default="prenom", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="participant",
            name="statut",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("evenement", "cotisant")},
        ),
    ]
